{
 "title": "Backend-Dashboard-basic",
 "description": "Grafana dashboard for the Expensy App Backend with 3 panels.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "🔢 Expenses Total Gauge",
   "type": "gauge",
   "description": "Total number of expenses(from MongoDB)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "expenses_total", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "📊 Total HTTP Requests with labels method, route, status",
   "type": "table",
   "description": "Total HTTP requests labeled with method, route, status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method, route, statusCode)(http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔁 Total HTTP Requests Over Time",
   "type": "timeseries",
   "description": "All HTTP requests without labels",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_overall_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}