{
 "title": "Dashboard-expensy-backend",
 "description": "Dashboard to to visualize the following Prometheus metrics:\n1. MongoDB Connection Status (mongo_connection_status)\n2. Total Expenses Recorded (expenses_total)\n3. Cumulative HTTP Requests (http_requests_overall_total)\n4. HTTP Requests Breakdown (http_requests_total)\n5. CPU Usage Over Time (process_cpu_seconds_total)",
 "time": { "from": "2025-04-17T10:52:47.429Z", "to": "2025-04-17T14:57:36.744Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MongoDB Connection Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mongo_connection_status" }
   ]
  },
  {
   "title": "🔢 Total Expenses Recorded",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "expenses_total" }
   ]
  },
  {
   "title": "🔁 Total HTTP Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(http_requests_overall_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📊 HTTP Requests Breakdown (Rate) with labels method, route, status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, route, statusCode) (rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "RAM Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  }
 ]
}