apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME=mongo
  MONGO_INITDB_ROOT_PASSWORD=mongo

  REDIS_HOST=redis
  REDIS_PASSWORD=redis

  PORT=8706 # Backend port