apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongo
  MONGO_INITDB_ROOT_PASSWORD: mongo123
  DATABASE_URI: mongodb://mongo:mongo123@mongodb-service:27017?authSource=admin # mongodb://<username>:<password>@<host>:<port>?authSource=admin
  redis-password: redis123