apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongo
<<<<<<< HEAD
  MONGO_INITDB_ROOT_PASSWORD: mongo123

  REDIS_HOST: redis
  REDIS_PASSWORD: redis123
=======
  MONGO_INITDB_ROOT_PASSWORD: mongo
  REDIS_HOST: redis
  REDIS_PASSWORD: redis
>>>>>>> 76675c1876f732efd464bfadf7bbbeefb00919ca
